server:
  port: 13001

spring:
  datasource:
    url: jdbc:mysql://192.168.6.200:3306/gmall_order?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    name: root
    type: com.zaxxer.hikari.HikariDataSource
  profiles:
    include: sharding