server:
  port: 8002

spring:
  datasource:
    url: jdbc:mysql://192.168.6.200:3306/gmall_user?useSSL=false
    password: 123456
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource